### ISSUE TITLE
the logo looks like a nazi symbol

### ISSUE THREAD

**Issue by thomaslule** [openspace42/aenigma#28]
Hi,

The logo looks very much like a nazi symbol and there is no understable reason for that.

**Comment by quexten** [comment]
![fbchhuv](https://user-images.githubusercontent.com/11866552/33212928-7a38e992-d125-11e7-82ff-8a511232d022.png)

Just changing 2 lines makes the first letter actually represent the characters 'A', 'E' and less controversial. I recommend changing this logo aswell.

**Comment by joselitosn** [comment]
Æ - https://en.wikipedia.org/wiki/%C3%86
卍 - https://en.wikipedia.org/wiki/Swastika

**Comment by quexten** [comment]
I mean in the end it's up to you what logo symbol you use. But the swastika is heavily stigmatized, and might send some unintended signals. Just my opinion. From the first paragraph of the wikipedia article joselitosn linked: 

> but in the 1930s, it became the main feature of Nazi symbolism as an emblem of Aryan race identity, and as a result, it has become stigmatized in the West by association with ideas of racism, hatred, and mass murder.

**Comment by nordurljosahvida** [comment]
Thanks guys, I appreciate the concern and the constructive criticism. Thanks for taking the time to redesign it @Quexten ;] It's actually somewhat intentional since I wanted to be as minimal about the logo as possible and kind of appreciate the slight provocation behind it, as it's actually a [sauwasticka](https://en.wikipedia.org/wiki/Sauwastika), it means something entirely different, and [this](https://github.com/openspace42/aenigma/blob/master/logo/aenigma_logo_evolution.pdf) is how it came to be like that. Also, the aenigma name is actually inspired by the original aenigma machine [with the inherent reference to the fact that nothing is 100% secure] and giving it that touch of apparent controversy kind of makes my day in a sense ;] Kidding aside, as with everything, the openspace community will decide. I'll definitely keep yours as valid and well appreciated votes. Thanks to all.

**Comment by thomaslule** [comment]
I think that maintaining a sort of "am I a nazi?" ambiguity (by keeping a symbol close to nazi imagery associated with the name of a machine used by the nazis) is neither funny nor provocative, but extremely offensive.

**Comment by nordurljosahvida** [comment]
As much as I appreciate you concern, if you still think there's any kind of ambiguity going on, I think you're intentionally looking for it, and by now you should probably already know how much I care about "people getting offended" especially when they're doing it all by themselves, but, in any event, you'll be happy to know that the community has voted, and although they agree with me, we also all agree that this issue is taking taking too much attention and focus away from the actual project, and I personally find it more fun and - yes - fair to be provocative and play around with people's perspectives of the world when I'm explicitly acting under my own name, and not the community's, so I've updated the logo, politically correctness is restored, and everyone can get back to their status-quo-compliant and contemporary-human-approved life with no more annoying and offensive stuff getting in their way. Before I delete the wiki entry, let me repost it here for immortality purposes:

## Are you a nazi?

No. For the record, [this](https://nikksno.io/enlightened-anarchy/) is what I think about the universe.

But since you're asking, let me dive down the rabbit hole:

1] For starters, the swasticka has been used across innumerable cultures and religions for millenia [often as a holy symbol for luck, light, and energy], and I'm definitely not going to join apparently every other human being into forcing it into oblivion because a small group of people decided to use it as well for their own dirty business. [[wiki](https://en.wikipedia.org/wiki/Swastika)]

2] This is a reverse / left-handed / counter-clockwise swasticka, also known as a [sauwastika](https://en.wikipedia.org/wiki/Sauwastika), which is intentionally called this way to distinguish it from the Third Reich flag's one [not that I care to be explicit about my distance from those ideals since I don't give a fuck about other people's opinions about me, especially when they're superficial and instinctive].

3] In any event all of this has absolutely no meaning since the evolution of the logo is [this](https://github.com/openspace42/aenigma/blob/master/logo/aenigma_logo_evolution.pdf) and it's the only thing that matters. The unexpectedly welcome surprise that it is provocative and makes people uncomfortable just makes it so much more fun and entertaining for me to sit back and watch.

4] This all just reminds me that I should be doing these creepy borderline things more often.

Have fun using aenigma and please do keep in mind I actually appreciate all feedback about the project :]
