### ISSUE TITLE
Job for sslh.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by ueberbiss** [openspace42/aenigma#30]
The sslh service fails after easyengine installation and the whole process fails. I cloned the latest version.

I run Ubuntu 16.04 on vultr.com.

systemctl status sslh.service shows the following:
```● sslh.service - LSB: sslh proxy ssl & ssh connections
   Loaded: loaded (/etc/init.d/sslh; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2017-12-01 17:58:51 CET; 1min 29s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 15678 ExecStart=/etc/init.d/sslh start (code=exited, status=1/FAILURE)

Dec 01 17:58:51 chinajon.me systemd[1]: Starting LSB: sslh proxy ssl & ssh connections...
Dec 01 17:58:51 chinajon.me sslh[15678]: Start services: sslh
Dec 01 17:58:51 chinajon.me sslh[15678]: localhost:https:bind: Address already in use
Dec 01 17:58:51 chinajon.me systemd[1]: sslh.service: Control process exited, code=exited status=1
Dec 01 17:58:51 chinajon.me systemd[1]: Failed to start LSB: sslh proxy ssl & ssh connections.
Dec 01 17:58:51 chinajon.me systemd[1]: sslh.service: Unit entered failed state.
Dec 01 17:58:51 chinajon.me systemd[1]: sslh.service: Failed with result 'exit-code'.
```
Any assistance would be greatly appreaciated.

**Comment by nordurljosahvida** [comment]
Hi there! It appears something is already listening on port 443 bound to localhost. Is this a clean machine or do you have other services running on it already? [webservers, etc...]

**Comment by ueberbiss** [comment]
It is a clean machine, but from what I can gather, nginx already listens on port 443, from the easyengine installation.

**Comment by nordurljosahvida** [comment]
Can you execute these commands on that machine please?

nslookup [yourhostname]
nslookup [yourhostname] 8.8.8.8
netstat -lntu

**Comment by nordurljosahvida** [comment]
@ueberbiss I've updated the SSLH install part so that it specifies your machine's IPv4 and IPv6 [if available] directly instead of specifying your hostname and letting SSLH determine your public address[es]. I think there's something strange going on with your PTR record or something DNS related that's tricking SSLH into thinking your hostname actually resolves to localhost [at least on your machine's DNS] therefore putting SSLH in the position to attempt binding to localhost, which is [correctly] already bound to nginx, therefore causing SSLH to fail. Try re-running the install now and let me know if it works for you!

**Comment by ueberbiss** [comment]
That works, thank you very much.

**Comment by nordurljosahvida** [comment]
@ueberbiss very good, thanks for your feedback!
