### ISSUE TITLE
installer error for letsencrypt

### ISSUE THREAD

**Issue by noerw** [openspace42/aenigma#46]
[The installer tries to create certs for all files in `/etc/letsencrypt/live/`](https://github.com/openspace42/aenigma/blob/3b88f23/tools/aenigma-create-push-certs#L134).
On my Debian 9 system I already installed certbot previously, and this directory contained besides the domains an `README` file, and the installer fails thus with:

```
Now creating all-in-one TLS certificate file for README...
```

Also, the installation of certbot did complete, I had to press ctrl+c to quit apt-get

**Comment by nordurljosahvida** [comment]
Interesting. Is a readme supposed to be in there? Going to look into it. 
Join us on aenigma@xc.os.vu!

**Comment by nordurljosahvida** [comment]
@noerw just pushed a fix which should solve the issue. Test it out with `bash setup -db -pb`.

**Comment by noerw** [comment]
yep, works as intended. thanks!

**Comment by jesusangelm** [comment]
Hi,
I'm having this error too, looks like `bash setup -db -pb` works, but now i'm not sure if this command is the correct for a first install.
When finish the script try to run ejabered but fail:

Now finally starting up ejabberd...

  Job for ejabberd.service failed because the control process exited with error code.
  See "systemctl status ejabberd.service" and "journalctl -xe" for details.


This is the "journalctl -xe"

https://pastebin.com/QqTUCKcD

I tried this in Ubuntu 18.04.1 and Debian 9.

another question: what are the minimum recommended resources? CPU cores, Ram, Disk?

**Comment by noerw** [comment]
@jesusangelm After instaling with the `README` issue, I had to fix the installation because ejabberd tries to load all files in `/etc/ssl/aenigma/` (`cert` section of `/etc/ejabberd/ejabberd.yml`).
This directory contained an empty `README.pem` file due to the issue in the op.
Remove it, and you should be good!

**Comment by nordurljosahvida** [comment]
@jesusangelm the `bash aenigma/setup -db -pb` is always correct, as aenigma does not distinguish between first install and thousandth run / re-install / upgrade. It is simply specifying that aenigma should be installed in its bleeding-edge version and not the stable release, since the fix I applied to fix @noerw's issue hasn't been included in a stable release yet.

**Comment by nordurljosahvida** [comment]
@jesusangelm If you executed with `-db -pb` everything should work alright. If you haven't, simply:
```
rm -r /etc/ssl/aenigma/
```
and then
```
bash aenigma/setup -db -pb
```
If you still have issues after this:
```
cat /var/log/ejabberd/error.log
```
and paste its output here.

**Comment by nordurljosahvida** [comment]
I'll release a stable version now with the fix anyway. @noerw thanks for helping out!

**Comment by jesusangelm** [comment]
Thanks! @noerw @nordurljosahvida 
that works now! ejabberd up and running!

**Comment by nordurljosahvida** [comment]
@jesusangelm Awesome! Definitely join us at aenigma@xc.os.vu to keep up to date with aenigma releases and our small but growing community! Also please share aenigma around if you like it and consider [becoming a patreon supporter](https://www.patreon.com/aenigma_xmpp) of our project. Thanks!
