### ISSUE TITLE
Ubuntu 18.04 root user authorization not possible using correct password 

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#51]
Something is broken with password setup while installing Aenigma.

I did a complete and successful (according to installer log) setup, received a new root password, but unfortunately not my current password neither old one works. It seems I'm locked out of my VDS and have to reinstall it once again.

```
ssh root@77.221.147.49 -p 42022
root@77.221.147.49's password:
Permission denied, please try again.
root@77.221.147.49's password:
Permission denied, please try again.
root@77.221.147.49's password:
root@77.221.147.49: Permission denied (publickey,password).
```

**Comment by rowie** [comment]
Last time testing works witout any problems. i only use public key for root login ... and i dont let the script changing my root pwd.

hope the devs could fix the two problems sooon. :-)

**Comment by nordurljosahvida** [comment]
@solus-hq by default `inception` [which is run by aenigma upon install] disables password-based SSH login, i should probably add a prompt so that the user is asked if they want to do it. If you saved the root password then you can likely access your VPS via your hosting provider's "emergency console" that goes directly to the machine VNC-style. Then enter root and your password and you should be in. If you manage post back and I'll guide you through re-enabling password-based login if you don't know how to. Sorry for the inconvenience!

**Comment by solus-hq** [comment]
I confirm this, I should have read the installation script output attentively. It's actually written in interactive installer, but I think it should be somehow marked **bold** =)

**Comment by nordurljosahvida** [comment]
@solus-hq @rowie I've update the inception function to ask before disallowing password-based logins. Thanks for the input.
