### ISSUE TITLE
Privacy flaw: connecting to TOR hidden service

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#67]
When trying to connect to aenigma instance via .onion service we always get an "incorrect certificate" error message which actually reveals REAL domain names pointing to our server making .onion usage useless in terms of anonymity. 

As one can see on the screenshot attached, we're trying to connect to Converse.js via TOR and our domains are revealed which is unacceptable I think.

<img width="1106" alt="Screen Shot 2019-05-19 at 22 25 00" src="https://user-images.githubusercontent.com/26515805/57996885-a024d500-7ad2-11e9-9898-efda9b3e8b40.png">

**Comment by nordurljosahvida** [comment]
Yes I stumbled onto this earlier, I got lost thinking about any potential solutions. LE is still in early stages of thinking about supporting .onion I think, so we're going to have to self-sign here. I'll think about a potential solution later today.

**Comment by solus-hq** [comment]
> LE is still in early stages of thinking about supporting .onion I think, so we're going to have to self-sign here. I'll think about a potential solution later today.

Yes, I know they're not allowing anyone to issue .onion certificates right now. There are some commercial solutions requiring you to reveal your full identity to obtain an .onion certificate (absolute madness)

**Comment by nordurljosahvida** [comment]
I'm 50% of the way fixing this with https://github.com/openspace42/aenigma/issues/71, will finish tomorrow and push a beta

**Comment by nordurljosahvida** [comment]
Fixed, any connection matching $domain [nginx, ejabberd, etc] should match LE wildcard cert for $domain, any connection to $additional_domain_1 should match its respective LE wildcard cert, any request to .onion hostname should return its self signed wildcard cert, and any *other* connection, to any unconfigured domain, made to that same machine, should return the onion self signed cert in order to avoid leaking clearnet domains via TLS cert mismatch. This is exactly what we wanted, right @solus-hq ? There are likely some edge cases I haven't tested so let's test this from any possible angle and see if it works as expected.

**Comment by solus-hq** [comment]
It is now fixed, can confirm

<img width="1112" alt="Screen Shot 2019-05-21 at 14 59 56" src="https://user-images.githubusercontent.com/26515805/58095593-0a756c80-7bdc-11e9-9962-74e7454f0b80.png">
