### ISSUE TITLE
Browser making requests to: cdn.conversejs.org

### ISSUE THREAD

**Issue by solus-hq** [openspace42/aenigma#69]
I don't think it's good that when we're using self-hosted Converse instance our browser is making connections to `cdn.conversejs.org`. I think that "self-hosted" paradigm is violated here, why can't we just have a full copy of Converse on our server?

**Comment by nordurljosahvida** [comment]
@solus-hq that is exactly our same philosophy and that's the reason why we fully build converse locally [JC even closed an issue on their side we were encountering when building]. The fact is that then we also need to remember to find and replace lines inside index.html to actually *use* the resources we just built ;] That's why we have testers like you guys, thanks!
