### ISSUE TITLE
single-node installation installs cluster tooling

### ISSUE THREAD

**Issue by noerw** [openspace42/aenigma#89]
Not sure if this is intended (v0.7.1):
My single-node installation also installed `etcd`, `patroni`, `postgres`, which only seem to be useful in a HA-deployment.

**Comment by solus-hq** [comment]
@nordurljosahvida seems to be quite busy and with lack of donations for these projects there's not much to be done unfortunately.

**Comment by nordurljosahvida** [comment]
@noerw this is intended yes so that A] we only need to develop one logic and one script and B] so that clusterization is easy to implement on an existing install. I'm looking into cocroachDB anyways, which could be the next logical step.

**Comment by nordurljosahvida** [comment]
@solus-hq true, thanks for checking in. The project has been dormant for the past 3 months as I have been working around the clock to get our new 3d printing shop up and running in the university area here in Milano, Italy, and because of this, and the fact that interest in the project seemed very limited, I had to keep aenigma on the back burner for a little bit. Now however, issues coming in, and 3 [3!] patrons donating every months, i can finally get back to development, and I'll keep you posted as soon as I'm back to coding. Thank you so much once again for your support.
